# Default values for cosignwebhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/eumel8/cosignwebhook/cosignwebhook
  pullPolicy: IfNotPresent
  tag: 4.2.0

imagePullSecrets: []
logLevel: info

nameOverride: ""
fullnameOverride: ""

# configuration admission controller
# https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/
admission:
  failurePolicy: Fail # or Ignore to allowed to continue in case of errors
  sideEffects: None # for out-of-band changes
  # name of the webhook
  webhook:
    name: webhook.example.com
  # list of excluded namespaces, comma-separated
  # exclude: default, kube-system, cattle-system

podAnnotations: {}

# minimal permissions for pod
podSecurityContext:
  fsGroup: 1000
  supplementalGroups:
  - 1000

# minimal permissions for container
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsUser: 1000
  runAsGroup: 1000

# service for Webhook endpoint and Monitoring
service:
  type: ClusterIP
  monitorPort: 80
  webhookPort: 443
  # targetPort and metricPort are static in the cosignwebhook app
  # configurable options for later
  targetPort: 8080
  metricPort: 8081

serviceMonitor:
  enabled: false

networkPolicy:
  enabled: false

# install a Grafana Dashboard (optional on a specific namespace)
grafanaDashboard:
  enabled: false
#   namespace: cattle-dashboards

# resources for InitContainer
initresources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# resources for Container
resources:
  limits:
    memory: 250Mi
    cpu: 500m
  requests:
    memory: 64Mi
    cpu: 300m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# verify all images before usage
# sccosign: verify the cosign cli image itself
# scwebhook: verify the cosign webhook image
cosign:
  image:
    repository: ghcr.io/sigstore/cosign/cosign
    tag: v2.0.0
    pullPolicy: IfNotPresent
  sccosign:
    key: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhyQCx0E9wQWSFI9ULGwy3BuRklnt
        IqozONbbdbqz11hlRJy9c7SG+hdcFl9jE9uE/dwtuwU2MqU9T/cN0YkWww==
        -----END PUBLIC KEY-----
  scwebhook:
    key: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENDN3HpXY2weMYRuuJbZnNczrOyns
        ZvVnR15G9EILCH8+elXkYy+4U70mR++XIL0iD8NhZ3kxfpFjxyHlnG5Snw==
        -----END PUBLIC KEY-----
