# Default values for cosignwebhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/eumel8/cosignwebhook/cosignwebhook
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# configuration admission controller
# https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/
admission:
  failurePolicy: Fail # or Ignore to allowed to continue in case of errors
  sideEffects: None # for out-of-band changes
  # name of the webhook
  webhook:
    name: webhook.example.com
  # list of excluded namespaces, comma-separated
  # exclude: default, kube-system, cattle-system

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  supplementalGroups:
  - 1000

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 443
  targetPort: 8080

initresources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

resources:
  limits:
    memory: 250Mi
    cpu: 500m
  requests:
    memory: 64Mi
    cpu: 300m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

cosign:
  image:
    repository: mtr.devops.telekom.de/mcsps/cosign
    tag: v1.8.0
    pullPolicy: IfNotPresent
  key: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgei36FSIhT8a9lOHs1Sem5KvmrT+
      Xi2EcyjLvaJzqu5n0TiygGeO4ZcU30A1PQv6xoI0xBxpyZAw7XeqzrRDOQ==
      -----END PUBLIC KEY-----

postjob:
  image:
    repository: ghcr.io/eumel8/cosignwebhook/cosignpostjob
    tag: 1.0.1
    pullPolicy: IfNotPresent
