# Default values for cosignwebhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/eumel8/navlinkswebhook/navlinkswebhook
  pullPolicy: IfNotPresent
  tag: 0.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# configuration admission controller
# https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/
admission:
  failurePolicy: Fail # or Ignore to allowed to continue in case of errors
  sideEffects: None # for out-of-band changes
  # name of the webhook
  webhook:
    name: webhook.example.com
  # list of excluded namespaces, comma-separated
  # exclude: default, kube-system, cattle-system

podAnnotations: {}

# minimal permissions for pod
podSecurityContext:
  fsGroup: 1000
  supplementalGroups:
  - 1000

# minimal permissions for container
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  runAsUser: 1000
  runAsGroup: 1000

# service for Webhook endpoint and Monitoring
service:
  type: ClusterIP
  monitorPort: 80
  webhookPort: 443
  targetPort: 8080

# resources for Container
resources:
  limits:
    memory: 250Mi
    cpu: 500m
  requests:
    memory: 64Mi
    cpu: 300m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
