repos:
  - repo: local
    hooks:
      - id: go-test
        name: go-unit-tests
        entry: make test-unit
        language: system
        types: [go]
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo
      - id: go-vet-repo-mod
      - id: go-fumpt-repo
        args: [ -l, -w ]
      - id: golangci-lint-repo-mod
        args: [ --config, .golangci.yaml, --, --fix ]
