{{- $secretname := include "cosignwebhook.fullname" . }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace  $secretname -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "cosignwebhook.fullname" . }}
  labels:
    {{- include "cosignwebhook.labels" . | nindent 4 }}
data:
{{- if or (not $secret) (not $secret.data) }}
  tls.crt: ""
  tls.key: ""
{{ else }}
  tls.crt: {{ index $secret.data "tls.crt" }}
  tls.key: {{ index $secret.data "tls.key" }}
{{- end }}
