apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "cosignwebhook.fullname" . }}
  labels:
    {{- include "cosignwebhook.labels" . | nindent 4 }}
data:
  tls.crt: ""
  tls.key: ""
