apiVersion: v1
kind: Service
metadata:
  name: {{ include "navlinkswebhook.fullname" . }}
  labels:
    {{- include "navlinkswebhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "navlinkswebhook.selectorLabels" . | nindent 4 }}
