apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosignwebhook.fullname" . }}
  labels:
    {{- include "cosignwebhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: {{ .Values.service.targetPort }}
    - name: metrics
      port: {{ .Values.service.monitorPort }}
      targetPort: {{ .Values.service.metricPort }}
  selector:
    {{- include "cosignwebhook.selectorLabels" . | nindent 4 }}
