---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: cosignwebhook
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxLZ0F3SUJBZ0lSQUp0SGF3OXhCOGpnS04xTVVEUkd4RUF3RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQXhNUlkyOXphV2R1TFhkbFltaHZiMnN0WTJFd0hoY05NalF3TVRFeU1UUXlNREExV2hjTgpNelF3TVRBNU1UUXlNREExV2pBWU1SWXdGQVlEVlFRREV3MWpiM05wWjI1M1pXSm9iMjlyTUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdUN2cXBtWCs1WE9ncFMvT1hPOTZ4VUdOTTRtVURZMWsKM3dBQm9PWThOcFpvay9BR1BSTzRWNHpwaGtjZVdJWHVJc1FRV1RFelFLalFtQi9QMUF1TllvTDJUSWRiRUJMMQptSEFnRFMxRGdwODIweXN4d2FGS3YzWHRUSjg2VTFWVndYSW1QeXFNODhTVjI3VDNGRWYvb2NEckYxb3IzQnpWCnZoTHVUTExaeXpPNDV4a3RQNUVueU1HQUtkbG5vU3F1V0dqa2lGSHh0bitITHpxbkEyYTBCeWQ0di9PdWpwdmcKYXpUYkdNL2F3QW5DRDZiQURZQVNOdXJjaWlvejlGNFM1VUwrSWpIemllU05ZNWpSMVBXNG9xNWEwS1F6ZjBybAp3R09Nd3FJbWZSVzRYeDQ2V21Sd2FJYmRPRDIvOFl5cEoxNGZ2Yk84R2duZVNmaCtMSUpRTlFJREFRQUJvNEdxCk1JR25NQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JTc0ZQVTQ4SEo2Z1VUMXpoT0ZBS3drV0RjVQpZVEJIQmdOVkhSRUVRREErZ2h0amIzTnBaMjUzWldKb2IyOXJMbU52YzJsbmJuZGxZbWh2YjJ1Q0gyTnZjMmxuCmJuZGxZbWh2YjJzdVkyOXphV2R1ZDJWaWFHOXZheTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKNVAKWDBKOW5HL2xBV1VLaHVrTnNVR25hdkcyOERCUWQwWFM5NElxSFFoQzlQamZOTGpicSs1QmhRNDJDOHMybXpmTwpSUzNwVjlmUldwUTR1blU5ZVp0V0l2Ty9IQ1Z1bmpKSUNrNEdNVzNpRTZ3a095U01kNjBQTm9RZnZ3UWlsRU9BCjRyZ2ZXK0dndlIxYlFwOHFTRHg0WEU4M0czNDNhbTdQcVpHNnVHRTRWMlExZnducnQxbmw0UmtSc1VPTlFhdzAKcUFEL0RNcEpEWXlDNi85bUdjQ3R0WUI0enVTWHd6SW1CZXRISFdHSUlLMmREQitOa3A0NDNEL0Vjb2hQU2hqQwpzN0hJaXlGR1pIMDMwejdRM3NTUjhUWk1wVUZBWXJ4OEY5bEVzWkJ2YmpZNVJTUFdTSXk2S29ibCtWUDZGOVFlCkZIQkdoMnkxcUh4ZkVVT3FDQzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdUN2cXBtWCs1WE9ncFMvT1hPOTZ4VUdOTTRtVURZMWszd0FCb09ZOE5wWm9rL0FHClBSTzRWNHpwaGtjZVdJWHVJc1FRV1RFelFLalFtQi9QMUF1TllvTDJUSWRiRUJMMW1IQWdEUzFEZ3A4MjB5c3gKd2FGS3YzWHRUSjg2VTFWVndYSW1QeXFNODhTVjI3VDNGRWYvb2NEckYxb3IzQnpWdmhMdVRMTFp5ek80NXhrdApQNUVueU1HQUtkbG5vU3F1V0dqa2lGSHh0bitITHpxbkEyYTBCeWQ0di9PdWpwdmdhelRiR00vYXdBbkNENmJBCkRZQVNOdXJjaWlvejlGNFM1VUwrSWpIemllU05ZNWpSMVBXNG9xNWEwS1F6ZjBybHdHT013cUltZlJXNFh4NDYKV21Sd2FJYmRPRDIvOFl5cEoxNGZ2Yk84R2duZVNmaCtMSUpRTlFJREFRQUJBb0lCQUYwaDhDNG5RK2ZhT2ZGdQpwR2VBdnMvRFgxa2hpRm4yRjMxaGJuRmtIQ3pxa0lYSENoQ1d5VkNVdEg2dnRodkQxbkdFUGxRc09pUEhlbnlECkVjREQrc0pIUWEvZmZ1QTVCak1JK0Z4UmVHTTBpaS90RnVNNDRpakJ4TGRMaWQ0Y09CcHowLzE3VWYzdmVteTUKTFh6M0Q4RkhZbHJUd1h3MHBLM1N1dWpVUktpcGFtL0oxSnNGeDVFYzZscndzZkFxc2FFOGJ5eXpmMXEzbzhMUApwc3doZ2xYS3RPdk5NK09UcXFyV3EveS94RXNHNFlETXl2L3FVL1RKaDV6V0I3cDdwbWpiSjdQMERBNXFwaTZ4CkEyditTNG1tQUNBSXRtSVp1U1c3aURPb01na1B4MEx4OWlVZ2M3S2RmTktPVW5kNTBTNU94VzJPakhYVXN2dFgKdHdmODhNRUNnWUVBMG5wS0cyN2o1MFZkNGduOFlNd2QrWjdKWFhMdk1sNkZXSWc5MktOSDRxdVpFTXV1TFJpWQphbUNwaFFqaU1heWxuZmRKdHB5ZXVrbGtTRm5waENuTzZQYjVzc0p4WkhQV3JpbU9KTVdUa1UwL2N5MVFwUU9uCkt1K0pGYnlzNStWQjlJNSs2ZEY2KzhEOVlLZEUwSTIzUVNKT0c4QWNIU0svNHdVd1NoZkVBUVVDZ1lFQTRBRWMKWDhIWHRaeGYyQzcyNjU2Z0NjdmNRVXg0NEw0NFFORW5HK0t2dWlhVXNqTG13RE9meisrVFAxdEFweVZ0UElmTAp1VXNGQkRzeFIvT3Q2bHphR2NaYWlBYktUSzZoMXRmS2w1UDRXcFEyNFZtVXg1V2QwWXUwbTNsY0tVMWJKcVV0CmVCdHJWSXI2VnRUWTJ0UW5oMlZoYjBKWlRvVDAxY1A4SWdJQStYRUNnWUVBZy80eXVTOTZkczkyaDhseFh4YkMKZVlkTmluQUlkMUwxVnNiaDJoalRmTi9WOXNWMHJrMHRVQkRjWGxScTNYSUN6cVNFc3FOWG0wVnBRVUk1Z2l0aAoyWkVBbUV6K0pWdkx0cDdTeUZhckswVUJWRzZIazJST0VrdnpjUkZJY1lqQkt1ZXR5VjRZUFFjVEh1am02ODdqCnJGSWlINThEUW5aSFZjd3NNMXJpRFMwQ2dZRUExcS9aM09Dd2Q4dStoRGhHeVAzSGpud0d4Y0tnRzIzVUJqTXUKazJoSVdWVytyNmRmUnBoenMxdCt1WHNnMU5GbkIxdHk0a3pIS3czOEptU2lxM3FBUWJHOGRLQmxaT2IrRHlYVQpja0FNQit3RFNTbU5FVmdRNEpOUDdxNTZxTThON0ZUazVqY0pRQWJPOVVlYjZ1Ym9WN2pQa0UxN3dHaG5LelZoCndjby8ydEVDZ1lCSkZIQTBIMFJZOGJERjBlcVVNeGVyWnNBM1lOY0RZS2JlMFE0dmJEbENLa3A3SFJRU3Q0Ri8KbTJSNThHemNzWU85VXNFbHhZTnNDdEJNVFMySFF0KytVbjloUGxrVWtqbjQ1dGtzUWVleDR2cW1FZkN2dmZPZQpKVWdRTi8vQ2JjdDJ5QTVNeVJuZEdrcEJBd0UyeUR2NlA2Skczai91dHVmRW1pVlJiNm5CU3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Service
metadata:
  name: cosignwebhook
  labels:
    app: cosignwebhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    app: cosignwebhook 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosignwebhook
  labels:
    app: cosignwebhook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cosignwebhook
  template:
    metadata:
      name: cosignwebhook 
      labels:
        app: cosignwebhook
    spec:
      initContainers:
      - args:
        - verify
        - --key
        - env://COSIGNPUBKEY
        - --insecure-ignore-tlog=true
        - mtr.devops.telekom.de/mcsps/cosign:v2.2.0
        command:
        - cosign
        env:
        - name: COSIGNPUBKEY
          value: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhyQCx0E9wQWSFI9ULGwy3BuRklnt
              IqozONbbdbqz11hlRJy9c7SG+hdcFl9jE9uE/dwtuwU2MqU9T/cN0YkWww==
              -----END PUBLIC KEY-----
        image: mtr.devops.telekom.de/mcsps/cosign:v2.2.0
        imagePullPolicy: Always
        name: sigcheckcosign
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      - args:
        - verify
        - --key
        - env://COSIGNPUBKEY
        - --insecure-ignore-tlog=true
        - mtr.devops.telekom.de/caas/cosignwebhook:4.0.4
        command:
        - cosign
        env:
        - name: COSIGNPUBKEY
          value: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENDN3HpXY2weMYRuuJbZnNczrOyns
              ZvVnR15G9EILCH8+elXkYy+4U70mR++XIL0iD8NhZ3kxfpFjxyHlnG5Snw==
              -----END PUBLIC KEY-----
        image: mtr.devops.telekom.de/mcsps/cosign:v2.2.0
        imagePullPolicy: Always
        name: sigcheckwebhook
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      containers:
        - name: cosignwebhook
          image: mtr.devops.telekom.de/caas/cosignwebhook:4.0.4
          imagePullPolicy: Always
          args:
            - -logLevel
            - info
          env:
          - name: COSIGNPUBKEY
            value: |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgei36FSIhT8a9lOHs1Sem5KvmrT+
                Xi2EcyjLvaJzqu5n0TiygGeO4ZcU30A1PQv6xoI0xBxpyZAw7XeqzrRDOQ==
                -----END PUBLIC KEY-----
          resources:
            limits:
              memory: 250Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            runAsUser: 1000
            runAsGroup: 1000
      securityContext:
        fsGroup: 1000
        supplementalGroups:
        - 1000
      serviceAccount: cosignwebhook
      volumes:
        - name: webhook-certs
          secret:
            secretName: cosignwebhook
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cosignwebhook
webhooks:
  - admissionReviewVersions:
    - v1
    name: cosignwebhook.caas.telekom.de
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["cosignwebhook", "kube-system", "cattle-system", "default"]
    clientConfig:
      service:
        name: cosignwebhook
        namespace: cosignwebhook
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKRENDQWd5Z0F3SUJBZ0lSQU1IbWFOZTdrdjNDYXVyVjFCWG5ObkF3RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQXhNUlkyOXphV2R1TFhkbFltaHZiMnN0WTJFd0hoY05NalF3TVRFeU1UUXlNREExV2hjTgpNelF3TVRBNU1UUXlNREExV2pBY01Sb3dHQVlEVlFRREV4RmpiM05wWjI0dGQyVmlhRzl2YXkxallUQ0NBU0l3CkRRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMbStSZXN5bWxVZlRpNW5lY0hRY2EwdTE2THIKTFExZkt3SUhJbVpscDB5OG83ZXd1UE55U1dwZ3lEOHFzVUlXeE1Wa3huQjM2ekdrTDloK0h2ekQ4RjF2ckRydApXcEF1ek5ieEwrc1pvd3ZZcjVRZWE3UXNSTDczVnovZncxWXVSeVk0Umg2elo4Rm1rTCswZjc1RWZpVzBLdjhiCnJwdHVucUtPdm9ERVVkL2F3R25ySXh4MC9KTWlIR091emVwWXlGWEtmMTRyOTlaMTQyMHRvdy9SUzZjT0t6dXEKSHlMTzJaeGJaQmtpeUY1TUVZbXk3L3JicU1kd29Ud29KOVJqeWVTQnlrbUwzbTQxQm9xeUIzckRBMkZObDlpdwpUc0JOTUJUOU1GYlhtWGp6aUZZeDZUU3lMRjQxODFQQmx2Sm5yeDBCMHlqbjduR0lmTGx4ZVdDV3NtTUNBd0VBCkFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2tNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU3NGUFU0OEhKNmdVVDF6aE9GQUt3awpXRGNVWVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUxON2FFbUtMVGpRbncranU0VkViZjJ4OWFtNEdlSmhOCjhobHVxZFMvdENYNHJmU0w1R1pWNGxFZ0lpSXNBWm9hOW9TRmU4bERxZTNhYXZIMnBOUHBRK3lHUldpdjlKUUUKZnJ0MkpzNC8xUlUvWHpiL3pWNHBqT3VXSCtwY29acGFVY20rc1JYYjFQeG5sMjlZYVdkdDRRdHhFNHJKVDlVSQp2U3dHWG1FaTR6MXpTWlNGRFh0Y24vQkFpMzZ2UHpnWDZxcG0vajhSSEFIK21mWXhZcExPQ2RpdWVmTkZLajRlCmtzU01RZjI4NW4rRDNWVUhlRHNFb2JQWDk5enIrOW1PdStvN044OVVCUXU1VzJhNFJIMkxmaFRWSUYzS3h1T3gKRXB0c1JXY0Z6OHRMcnlHOTBNcXBkU3JmZ0ljZXdNalhyV25RMi9TOVkraXNMUENGU3FPRGpRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
