---
apiVersion: v1
kind: Service
metadata:
  name: cosignwebhook
  labels:
    app: cosignwebhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    app: cosignwebhook 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosignwebhook
  labels:
    app: cosignwebhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosignwebhook
  template:
    metadata:
      name: cosignwebhook 
      labels:
        app: cosignwebhook
    spec:
      containers:
        - name: webhook
          image: mtr.devops.telekom.de/caas/cosignwebhook:main
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 250Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            runAsUser: 1000
            runAsGroup: 1000
      securityContext:
        fsGroup: 1000
        supplementalGroups:
        - 1000
      serviceAccount: cosignwebhook
      volumes:
        - name: webhook-certs
          secret:
            secretName: cosignwebhook
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cosignwebhook
webhooks:
  - admissionReviewVersions:
    - v1
    name: cosignwebhook.caas.telekom.de
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["cosignwebhook", "kube-system", "cattle-system", "default"]
    clientConfig:
      service:
        name: cosignwebhook
        namespace: cosignwebhook
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZOekNDQXgrZ0F3SUJBZ0lVTW1ndFRsM2VnOWplZjRYZ1oyVEkzSXdTQXcwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF3d1JaM0oxYlhCNUxtZHlkVzF3ZVM1emRtTXdIaGNOTWpNd01UQXhNVFl6T1RJdwpXaGNOTXpJeE1qSTVNVFl6T1RJd1dqQWNNUm93R0FZRFZRUUREQkZuY25WdGNIa3VaM0oxYlhCNUxuTjJZekNDCkFpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTEk3cWpoTnhYUHM3Q0JocVdVcXZ6UjAKVEhJSEJqZFl1Q00wOG1lcXFQWk9nVzRCVHZrR3hYSDl4dFhucWV6Z2NjZnNDMTRRTDdJZlU1N2xOTnhaaWREagp0SVl3Rzg3Z3EzMzdZcjgvZDIzTUVJTllCcGJ3VDhLRHFmanJxRks4U3pxSHlUMWg2WEkvRmpoUktKZUtMODdjCjFML21QNDJtSnY4K1R0TDIzU21yN3ZVdTk5aGtibW9XRzdsK0VKNnU4TEg1dVlhbXJ2ZHdueC9hZW1iUnlOZXMKdTV1STVZN2MrK1Y3OGtlbTNjNXNxQmlkcW81OElxQllpZ2NOZklac1pqZWF3a2ZUcmFwNFZHRXdjalMvQWFkcgo2c2VuUmNocVJyc295S3c3UnZCTTdydWEyMS9MdFBSeEZNR0lHSThPa0ZTWm4vd3ZpMDMxVmRTbDBYN3o5ZjJsCjdnazFNSUxOVGdFZEE0S3BUdW5ONGdRVG1UQW5PRTdVbncxOGhCN2xERmFrR3VKMVNEaGNDSXRTY3RidXJVUXMKWnVra1BpRTRnb0laSFhoYkZ5d042R2VpZDdvZGJ3bUYxOUZRaEZzcmREcktvZEEyWVdUL1hlWlNaVm91UXlsKwoyWXA1VGgwRG5BSzBKb0VwOHZHTjlVd0JZdVFZSXVkNjZ1ZGRPR0JUdFd5ekIwNjA2QmNabGxSbjQ3MVlsQ1dRCnQvZXQwU1VuYzhvUDFtTlpFbkFTUFNJV3FqdVNNRkNuWHZ6aDNGdXJOR3ZSRWk1Z3V5ajlKNTY1bTByWFRlVlEKR1ZFMHVTdEMrU3pRWXBsTW5GU3ZmdVVJeG40ZjNYWThCTlhyT05jeSt0eUl1NWk0RDZQT0Y5RUFqZ0RMc0xhegp6U2t1c3d0N3p0T1NWYkRWNDVYekFnTUJBQUdqY1RCdk1CMEdBMVVkRGdRV0JCUmVuOWp4MG9XRnQ2UHZFd2UvCjl5c3NweTF2YVRBZkJnTlZIU01FR0RBV2dCUmVuOWp4MG9XRnQ2UHZFd2UvOXlzc3B5MXZhVEFQQmdOVkhSTUIKQWY4RUJUQURBUUgvTUJ3R0ExVWRFUVFWTUJPQ0VXZHlkVzF3ZVM1bmNuVnRjSGt1YzNaak1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUNBUUJPRW1zdk5VbkQrYkFOOUJqUHg5cGJRaTN5dFRCcEk4Y2hNWXllNHViYS9CUXpQRGpvCjNkcmxjTjA1ZTBoeWNSVG1rOXBYbVR4YWIvSkhrNWgzTmV2cFNIWVpQK2NvNlVOSkhLY2lkaXIwRmMzcEZLZEYKVmFEV3BIU2I0eGJjYUlVbnhKL3E1blNQQWRlQ0s2RGtoZlkxWXBibHpsaTArY2RWUWUyU2xLVVczRENKWkVmTgo0cmgvVm15V2JPZEVMc0NnWVkwN3lUVmcwcEM3Nm1pZVFodDd5RXBESTNVSG05UjArS1F6bWh6bjB1RU5ySjF6CnpIYUt3M3hlb3UxSG10dU04cXo1TWk4bXN1bTBVQ2FEeVRkc216L253OC9nNE9SQVFLRXlaOFBGVjM0YlFzM2QKNkpiTDVSQTVlS1lmOEc2WkpZbmoySWU3aFFnaThHR0hPbmJXb1ArVStpNkRXcU9PaU1IbWdZaURFTG5SQkxubAp4aHc2ajR1bS9vQTZYMVg4UnZlcEM0UnVoNTJxL0kvbktTM1N5MENBWUQ5YUhXN0RncEdrQ1F3TVh0VTIzV25xCi9IU1pDWmViZzhnZWg2b2pRMzN2aHFZV212ekF3bkdvQnNVN3RLRklaV0xidmV0WG1jdEhsYStiVTZTaUgvTzIKekxwSzRhbVBsMC96S0tPcXBkWUNCa0w2ODIweXVkMVRxYUtjK1ZyeFo1RVBvOEx4SGttWTg2QzRvaFNiZWZyLwozU2Z6bk8wcW0wMlRsL2NUYW44dm5CNjdEMVJMMlpocEVmVlJ4THE1R2Jnd3p4cTN0S0ZOdEkrelV0b2M4NkJECk9XalNmYzlLOVR6Y2dIWDhHZER4dFZJRy9NcFZSVUgyVkFSM0p3V2NRQi8vTExzTVplK1FqbmhwQXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
