---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cosignwebhook
  name: cosignwebhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cosignwebhook
  labels:
    app: cosignwebhook
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    - serviceaccounts
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cosignwebhook
  labels:
    app: cosignwebhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cosignwebhook
subjects:
- kind: ServiceAccount
  name: cosignwebhook
  namespace: cosignwebhook
